from __future__ import annotations
from typing import List, Dict, Any

PYTEST_HEADER = """# Auto-generated by CodeAssistant
import pytest
"""

HYPOTHESIS_HEADER = """from hypothesis import given, strategies as st
"""

def make_test_module(module_rel: str, funcs: List[Dict[str, Any]], use_hypothesis: bool) -> str:
    lines = [PYTEST_HEADER]
    if use_hypothesis:
        lines.append(HYPOTHESIS_HEADER)

    mod = module_rel.replace("/", ".").replace(".py", "")
    lines.append(f"import importlib\n\nMOD = importlib.import_module('{mod}')\n")

    for f in funcs:
        name = f["name"]
        args = f["args"]
        call_args = ", ".join(["None" for _ in args])

        lines.append(f"\n\ndef test_{name}__basic_smoke():")
        lines.append("    # TODO: 根据真实语义替换 None，补充断言")
        lines.append(f"    out = getattr(MOD, '{name}')({call_args})")
        lines.append("    assert out is not None or out is None\n")

        lines.append(f"\n\ndef test_{name}__edge_cases():")
        lines.append("    # TODO: 空输入/极值/非法类型/异常路径")
        lines.append("    assert True\n")

        if use_hypothesis:
            lines.append("\n@given(st.integers(), st.integers())")
            lines.append(f"def test_{name}__property_based(a, b):")
            lines.append("    try:")
            lines.append(f"        _ = getattr(MOD, '{name}')(a, b)")
            lines.append("    except TypeError:")
            lines.append("        pytest.skip('signature mismatch for hypothesis template')\n")

    return "\n".join(lines)
