# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../TheAlgorithms__Python').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../TheAlgorithms__Python/bit_manipulation/single_bit_manipulation_operations.py'
MOD_NAME = 'mod_bit_manipulation_single_bit_manipulation_operations_250dcfb5'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_set_bit__basic_smoke():
    try:
        out = getattr(MOD, 'set_bit')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_set_bit__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_set_bit__property_based(a, b):
    try:
        _ = getattr(MOD, 'set_bit')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_clear_bit__basic_smoke():
    try:
        out = getattr(MOD, 'clear_bit')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_clear_bit__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_clear_bit__property_based(a, b):
    try:
        _ = getattr(MOD, 'clear_bit')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_flip_bit__basic_smoke():
    try:
        out = getattr(MOD, 'flip_bit')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_flip_bit__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_flip_bit__property_based(a, b):
    try:
        _ = getattr(MOD, 'flip_bit')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_is_bit_set__basic_smoke():
    try:
        out = getattr(MOD, 'is_bit_set')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_is_bit_set__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_is_bit_set__property_based(a, b):
    try:
        _ = getattr(MOD, 'is_bit_set')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get_bit__basic_smoke():
    try:
        out = getattr(MOD, 'get_bit')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_bit__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_bit__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_bit')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
