# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../ageron__handson-ml').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '_notebooks/nb_02_end_to_end_machine_learning_project_40e60435.py'
MOD_NAME = 'nb_02_end_to_end_machine_learning_project_40e60435'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_save_fig__basic_smoke():
    try:
        out = getattr(MOD, 'save_fig')(None, None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_save_fig__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_save_fig__property_based(a, b):
    try:
        _ = getattr(MOD, 'save_fig')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_fetch_housing_data__basic_smoke():
    try:
        out = getattr(MOD, 'fetch_housing_data')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_fetch_housing_data__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_fetch_housing_data__property_based(a, b):
    try:
        _ = getattr(MOD, 'fetch_housing_data')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_load_housing_data__basic_smoke():
    try:
        out = getattr(MOD, 'load_housing_data')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_load_housing_data__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_load_housing_data__property_based(a, b):
    try:
        _ = getattr(MOD, 'load_housing_data')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_split_train_test__basic_smoke():
    try:
        out = getattr(MOD, 'split_train_test')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_split_train_test__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_split_train_test__property_based(a, b):
    try:
        _ = getattr(MOD, 'split_train_test')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_test_set_check__basic_smoke():
    try:
        out = getattr(MOD, 'test_set_check')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_test_set_check__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_test_set_check__property_based(a, b):
    try:
        _ = getattr(MOD, 'test_set_check')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_split_train_test_by_id__basic_smoke():
    try:
        out = getattr(MOD, 'split_train_test_by_id')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_split_train_test_by_id__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_split_train_test_by_id__property_based(a, b):
    try:
        _ = getattr(MOD, 'split_train_test_by_id')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_test_set_check__basic_smoke():
    try:
        out = getattr(MOD, 'test_set_check')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_test_set_check__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_test_set_check__property_based(a, b):
    try:
        _ = getattr(MOD, 'test_set_check')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_test_set_check__basic_smoke():
    try:
        out = getattr(MOD, 'test_set_check')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_test_set_check__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_test_set_check__property_based(a, b):
    try:
        _ = getattr(MOD, 'test_set_check')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_income_cat_proportions__basic_smoke():
    try:
        out = getattr(MOD, 'income_cat_proportions')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_income_cat_proportions__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_income_cat_proportions__property_based(a, b):
    try:
        _ = getattr(MOD, 'income_cat_proportions')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_add_extra_features__basic_smoke():
    try:
        out = getattr(MOD, 'add_extra_features')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_add_extra_features__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_add_extra_features__property_based(a, b):
    try:
        _ = getattr(MOD, 'add_extra_features')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_display_scores__basic_smoke():
    try:
        out = getattr(MOD, 'display_scores')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_display_scores__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_display_scores__property_based(a, b):
    try:
        _ = getattr(MOD, 'display_scores')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_indices_of_top_k__basic_smoke():
    try:
        out = getattr(MOD, 'indices_of_top_k')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_indices_of_top_k__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_indices_of_top_k__property_based(a, b):
    try:
        _ = getattr(MOD, 'indices_of_top_k')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
