# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../TheAlgorithms__Python').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../TheAlgorithms__Python/ciphers/elgamal_key_generator.py'
MOD_NAME = 'mod_ciphers_elgamal_key_generator_e2eab36a'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_primitive_root__basic_smoke():
    try:
        out = getattr(MOD, 'primitive_root')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_primitive_root__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_primitive_root__property_based(a, b):
    try:
        _ = getattr(MOD, 'primitive_root')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_generate_key__basic_smoke():
    try:
        out = getattr(MOD, 'generate_key')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_generate_key__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_generate_key__property_based(a, b):
    try:
        _ = getattr(MOD, 'generate_key')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_make_key_files__basic_smoke():
    try:
        out = getattr(MOD, 'make_key_files')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_make_key_files__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_make_key_files__property_based(a, b):
    try:
        _ = getattr(MOD, 'make_key_files')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_main__basic_smoke():
    try:
        out = getattr(MOD, 'main')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_main__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_main__property_based(a, b):
    try:
        _ = getattr(MOD, 'main')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
