# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../Netflix__security_monkey').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../Netflix__security_monkey/security_monkey/account_manager.py'
MOD_NAME = 'mod_security_monkey_account_manager_9f8cfb03'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_load_all_account_types__basic_smoke():
    try:
        out = getattr(MOD, 'load_all_account_types')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_load_all_account_types__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_load_all_account_types__property_based(a, b):
    try:
        _ = getattr(MOD, 'load_all_account_types')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get_account_by_id__basic_smoke():
    try:
        out = getattr(MOD, 'get_account_by_id')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_account_by_id__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_account_by_id__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_account_by_id')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get_account_by_name__basic_smoke():
    try:
        out = getattr(MOD, 'get_account_by_name')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_account_by_name__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_account_by_name__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_account_by_name')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_delete_account_by_id__basic_smoke():
    try:
        out = getattr(MOD, 'delete_account_by_id')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_delete_account_by_id__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_delete_account_by_id__property_based(a, b):
    try:
        _ = getattr(MOD, 'delete_account_by_id')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_delete_account_by_name__basic_smoke():
    try:
        out = getattr(MOD, 'delete_account_by_name')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_delete_account_by_name__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_delete_account_by_name__property_based(a, b):
    try:
        _ = getattr(MOD, 'delete_account_by_name')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_bulk_disable_accounts__basic_smoke():
    try:
        out = getattr(MOD, 'bulk_disable_accounts')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_bulk_disable_accounts__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_bulk_disable_accounts__property_based(a, b):
    try:
        _ = getattr(MOD, 'bulk_disable_accounts')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_bulk_enable_accounts__basic_smoke():
    try:
        out = getattr(MOD, 'bulk_enable_accounts')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_bulk_enable_accounts__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_bulk_enable_accounts__property_based(a, b):
    try:
        _ = getattr(MOD, 'bulk_enable_accounts')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
