# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../Netflix__security_monkey').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../Netflix__security_monkey/security_monkey/manage.py'
MOD_NAME = 'mod_security_monkey_manage_0639855e'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_drop_db__basic_smoke():
    try:
        out = getattr(MOD, 'drop_db')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_drop_db__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_drop_db__property_based(a, b):
    try:
        _ = getattr(MOD, 'drop_db')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_run_change_reporter__basic_smoke():
    try:
        out = getattr(MOD, 'run_change_reporter')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_run_change_reporter__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_run_change_reporter__property_based(a, b):
    try:
        _ = getattr(MOD, 'run_change_reporter')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_find_changes__basic_smoke():
    try:
        out = getattr(MOD, 'find_changes')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_find_changes__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_find_changes__property_based(a, b):
    try:
        _ = getattr(MOD, 'find_changes')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_audit_changes__basic_smoke():
    try:
        out = getattr(MOD, 'audit_changes')(None, None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_audit_changes__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_audit_changes__property_based(a, b):
    try:
        _ = getattr(MOD, 'audit_changes')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_delete_unjustified_issues__basic_smoke():
    try:
        out = getattr(MOD, 'delete_unjustified_issues')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_delete_unjustified_issues__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_delete_unjustified_issues__property_based(a, b):
    try:
        _ = getattr(MOD, 'delete_unjustified_issues')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_export_environment_summary__basic_smoke():
    try:
        out = getattr(MOD, 'export_environment_summary')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_export_environment_summary__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_export_environment_summary__property_based(a, b):
    try:
        _ = getattr(MOD, 'export_environment_summary')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_backup_config_to_json__basic_smoke():
    try:
        out = getattr(MOD, 'backup_config_to_json')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_backup_config_to_json__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_backup_config_to_json__property_based(a, b):
    try:
        _ = getattr(MOD, 'backup_config_to_json')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_sync_jira__basic_smoke():
    try:
        out = getattr(MOD, 'sync_jira')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_sync_jira__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_sync_jira__property_based(a, b):
    try:
        _ = getattr(MOD, 'sync_jira')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_delete_revisions_by_date__basic_smoke():
    try:
        out = getattr(MOD, 'delete_revisions_by_date')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_delete_revisions_by_date__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_delete_revisions_by_date__property_based(a, b):
    try:
        _ = getattr(MOD, 'delete_revisions_by_date')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_clear_expired_exceptions__basic_smoke():
    try:
        out = getattr(MOD, 'clear_expired_exceptions')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_clear_expired_exceptions__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_clear_expired_exceptions__property_based(a, b):
    try:
        _ = getattr(MOD, 'clear_expired_exceptions')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_amazon_accounts__basic_smoke():
    try:
        out = getattr(MOD, 'amazon_accounts')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_amazon_accounts__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_amazon_accounts__property_based(a, b):
    try:
        _ = getattr(MOD, 'amazon_accounts')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_create_user__basic_smoke():
    try:
        out = getattr(MOD, 'create_user')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_create_user__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_create_user__property_based(a, b):
    try:
        _ = getattr(MOD, 'create_user')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_toggle_active_user__basic_smoke():
    try:
        out = getattr(MOD, 'toggle_active_user')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_toggle_active_user__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_toggle_active_user__property_based(a, b):
    try:
        _ = getattr(MOD, 'toggle_active_user')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_disable_accounts__basic_smoke():
    try:
        out = getattr(MOD, 'disable_accounts')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_disable_accounts__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_disable_accounts__property_based(a, b):
    try:
        _ = getattr(MOD, 'disable_accounts')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_enable_accounts__basic_smoke():
    try:
        out = getattr(MOD, 'enable_accounts')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_enable_accounts__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_enable_accounts__property_based(a, b):
    try:
        _ = getattr(MOD, 'enable_accounts')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_add_override_score__basic_smoke():
    try:
        out = getattr(MOD, 'add_override_score')(None, None, None, None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_add_override_score__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_add_override_score__property_based(a, b):
    try:
        _ = getattr(MOD, 'add_override_score')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_add_override_scores__basic_smoke():
    try:
        out = getattr(MOD, 'add_override_scores')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_add_override_scores__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_add_override_scores__property_based(a, b):
    try:
        _ = getattr(MOD, 'add_override_scores')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_delete_account__basic_smoke():
    try:
        out = getattr(MOD, 'delete_account')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_delete_account__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_delete_account__property_based(a, b):
    try:
        _ = getattr(MOD, 'delete_account')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_add_watcher_config__basic_smoke():
    try:
        out = getattr(MOD, 'add_watcher_config')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_add_watcher_config__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_add_watcher_config__property_based(a, b):
    try:
        _ = getattr(MOD, 'add_watcher_config')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_fetch_aws_canonical_ids__basic_smoke():
    try:
        out = getattr(MOD, 'fetch_aws_canonical_ids')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_fetch_aws_canonical_ids__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_fetch_aws_canonical_ids__property_based(a, b):
    try:
        _ = getattr(MOD, 'fetch_aws_canonical_ids')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_clean_stale_issues__basic_smoke():
    try:
        out = getattr(MOD, 'clean_stale_issues')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_clean_stale_issues__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_clean_stale_issues__property_based(a, b):
    try:
        _ = getattr(MOD, 'clean_stale_issues')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_sync_swag__basic_smoke():
    try:
        out = getattr(MOD, 'sync_swag')(None, None, None, None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_sync_swag__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_sync_swag__property_based(a, b):
    try:
        _ = getattr(MOD, 'sync_swag')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_sync_networks__basic_smoke():
    try:
        out = getattr(MOD, 'sync_networks')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_sync_networks__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_sync_networks__property_based(a, b):
    try:
        _ = getattr(MOD, 'sync_networks')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_main__basic_smoke():
    try:
        out = getattr(MOD, 'main')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_main__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_main__property_based(a, b):
    try:
        _ = getattr(MOD, 'main')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
