# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../pallets__flask').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../pallets__flask/src/flask/templating.py'
MOD_NAME = 'mod_src_flask_templating_61f1eb03'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_render_template__basic_smoke():
    try:
        out = getattr(MOD, 'render_template')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_render_template__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_render_template__property_based(a, b):
    try:
        _ = getattr(MOD, 'render_template')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_render_template_string__basic_smoke():
    try:
        out = getattr(MOD, 'render_template_string')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_render_template_string__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_render_template_string__property_based(a, b):
    try:
        _ = getattr(MOD, 'render_template_string')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_stream_template__basic_smoke():
    try:
        out = getattr(MOD, 'stream_template')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_stream_template__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_stream_template__property_based(a, b):
    try:
        _ = getattr(MOD, 'stream_template')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_stream_template_string__basic_smoke():
    try:
        out = getattr(MOD, 'stream_template_string')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_stream_template_string__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_stream_template_string__property_based(a, b):
    try:
        _ = getattr(MOD, 'stream_template_string')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
