# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../pallets__flask').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../pallets__flask/examples/tutorial/flaskr/blog.py'
MOD_NAME = 'mod_examples_tutorial_flaskr_blog_eac5c75f'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_index__basic_smoke():
    try:
        out = getattr(MOD, 'index')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_index__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_index__property_based(a, b):
    try:
        _ = getattr(MOD, 'index')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get_post__basic_smoke():
    try:
        out = getattr(MOD, 'get_post')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_post__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_post__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_post')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_create__basic_smoke():
    try:
        out = getattr(MOD, 'create')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_create__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_create__property_based(a, b):
    try:
        _ = getattr(MOD, 'create')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_update__basic_smoke():
    try:
        out = getattr(MOD, 'update')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_update__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_update__property_based(a, b):
    try:
        _ = getattr(MOD, 'update')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_delete__basic_smoke():
    try:
        out = getattr(MOD, 'delete')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_delete__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_delete__property_based(a, b):
    try:
        _ = getattr(MOD, 'delete')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
