# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../kennethreitz__requests').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../kennethreitz__requests/src/requests/api.py'
MOD_NAME = 'mod_src_requests_api_8d535495'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_request__basic_smoke():
    try:
        out = getattr(MOD, 'request')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_request__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_request__property_based(a, b):
    try:
        _ = getattr(MOD, 'request')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get__basic_smoke():
    try:
        out = getattr(MOD, 'get')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get__property_based(a, b):
    try:
        _ = getattr(MOD, 'get')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_options__basic_smoke():
    try:
        out = getattr(MOD, 'options')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_options__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_options__property_based(a, b):
    try:
        _ = getattr(MOD, 'options')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_head__basic_smoke():
    try:
        out = getattr(MOD, 'head')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_head__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_head__property_based(a, b):
    try:
        _ = getattr(MOD, 'head')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_post__basic_smoke():
    try:
        out = getattr(MOD, 'post')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_post__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_post__property_based(a, b):
    try:
        _ = getattr(MOD, 'post')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_put__basic_smoke():
    try:
        out = getattr(MOD, 'put')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_put__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_put__property_based(a, b):
    try:
        _ = getattr(MOD, 'put')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_patch__basic_smoke():
    try:
        out = getattr(MOD, 'patch')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_patch__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_patch__property_based(a, b):
    try:
        _ = getattr(MOD, 'patch')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_delete__basic_smoke():
    try:
        out = getattr(MOD, 'delete')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_delete__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_delete__property_based(a, b):
    try:
        _ = getattr(MOD, 'delete')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
