# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../TheAlgorithms__Python').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../TheAlgorithms__Python/bit_manipulation/power_of_4.py'
MOD_NAME = 'mod_bit_manipulation_power_of_4_476066e5'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_power_of_4__basic_smoke():
    try:
        out = getattr(MOD, 'power_of_4')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_power_of_4__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_power_of_4__property_based(a, b):
    try:
        _ = getattr(MOD, 'power_of_4')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
