# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../TheAlgorithms__Python').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../TheAlgorithms__Python/ciphers/beaufort_cipher.py'
MOD_NAME = 'mod_ciphers_beaufort_cipher_d0b3420a'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_generate_key__basic_smoke():
    try:
        out = getattr(MOD, 'generate_key')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_generate_key__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_generate_key__property_based(a, b):
    try:
        _ = getattr(MOD, 'generate_key')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_cipher_text__basic_smoke():
    try:
        out = getattr(MOD, 'cipher_text')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_cipher_text__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_cipher_text__property_based(a, b):
    try:
        _ = getattr(MOD, 'cipher_text')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_original_text__basic_smoke():
    try:
        out = getattr(MOD, 'original_text')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_original_text__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_original_text__property_based(a, b):
    try:
        _ = getattr(MOD, 'original_text')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_main__basic_smoke():
    try:
        out = getattr(MOD, 'main')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_main__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_main__property_based(a, b):
    try:
        _ = getattr(MOD, 'main')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
