# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../TheAlgorithms__Python').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../TheAlgorithms__Python/audio_filters/butterworth_filter.py'
MOD_NAME = 'mod_audio_filters_butterworth_filter_f5c5343f'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_make_lowpass__basic_smoke():
    try:
        out = getattr(MOD, 'make_lowpass')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_make_lowpass__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_make_lowpass__property_based(a, b):
    try:
        _ = getattr(MOD, 'make_lowpass')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_make_highpass__basic_smoke():
    try:
        out = getattr(MOD, 'make_highpass')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_make_highpass__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_make_highpass__property_based(a, b):
    try:
        _ = getattr(MOD, 'make_highpass')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_make_bandpass__basic_smoke():
    try:
        out = getattr(MOD, 'make_bandpass')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_make_bandpass__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_make_bandpass__property_based(a, b):
    try:
        _ = getattr(MOD, 'make_bandpass')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_make_allpass__basic_smoke():
    try:
        out = getattr(MOD, 'make_allpass')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_make_allpass__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_make_allpass__property_based(a, b):
    try:
        _ = getattr(MOD, 'make_allpass')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_make_peak__basic_smoke():
    try:
        out = getattr(MOD, 'make_peak')(None, None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_make_peak__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_make_peak__property_based(a, b):
    try:
        _ = getattr(MOD, 'make_peak')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_make_lowshelf__basic_smoke():
    try:
        out = getattr(MOD, 'make_lowshelf')(None, None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_make_lowshelf__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_make_lowshelf__property_based(a, b):
    try:
        _ = getattr(MOD, 'make_lowshelf')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_make_highshelf__basic_smoke():
    try:
        out = getattr(MOD, 'make_highshelf')(None, None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_make_highshelf__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_make_highshelf__property_based(a, b):
    try:
        _ = getattr(MOD, 'make_highshelf')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
