# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../kennethreitz__requests').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../kennethreitz__requests/src/requests/utils.py'
MOD_NAME = 'mod_src_requests_utils_160415f0'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_dict_to_sequence__basic_smoke():
    try:
        out = getattr(MOD, 'dict_to_sequence')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_dict_to_sequence__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_dict_to_sequence__property_based(a, b):
    try:
        _ = getattr(MOD, 'dict_to_sequence')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_super_len__basic_smoke():
    try:
        out = getattr(MOD, 'super_len')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_super_len__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_super_len__property_based(a, b):
    try:
        _ = getattr(MOD, 'super_len')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get_netrc_auth__basic_smoke():
    try:
        out = getattr(MOD, 'get_netrc_auth')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_netrc_auth__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_netrc_auth__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_netrc_auth')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_guess_filename__basic_smoke():
    try:
        out = getattr(MOD, 'guess_filename')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_guess_filename__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_guess_filename__property_based(a, b):
    try:
        _ = getattr(MOD, 'guess_filename')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_extract_zipped_paths__basic_smoke():
    try:
        out = getattr(MOD, 'extract_zipped_paths')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_extract_zipped_paths__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_extract_zipped_paths__property_based(a, b):
    try:
        _ = getattr(MOD, 'extract_zipped_paths')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_atomic_open__basic_smoke():
    try:
        out = getattr(MOD, 'atomic_open')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_atomic_open__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_atomic_open__property_based(a, b):
    try:
        _ = getattr(MOD, 'atomic_open')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_from_key_val_list__basic_smoke():
    try:
        out = getattr(MOD, 'from_key_val_list')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_from_key_val_list__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_from_key_val_list__property_based(a, b):
    try:
        _ = getattr(MOD, 'from_key_val_list')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_to_key_val_list__basic_smoke():
    try:
        out = getattr(MOD, 'to_key_val_list')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_to_key_val_list__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_to_key_val_list__property_based(a, b):
    try:
        _ = getattr(MOD, 'to_key_val_list')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_parse_list_header__basic_smoke():
    try:
        out = getattr(MOD, 'parse_list_header')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_parse_list_header__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_parse_list_header__property_based(a, b):
    try:
        _ = getattr(MOD, 'parse_list_header')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_parse_dict_header__basic_smoke():
    try:
        out = getattr(MOD, 'parse_dict_header')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_parse_dict_header__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_parse_dict_header__property_based(a, b):
    try:
        _ = getattr(MOD, 'parse_dict_header')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_unquote_header_value__basic_smoke():
    try:
        out = getattr(MOD, 'unquote_header_value')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_unquote_header_value__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_unquote_header_value__property_based(a, b):
    try:
        _ = getattr(MOD, 'unquote_header_value')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_dict_from_cookiejar__basic_smoke():
    try:
        out = getattr(MOD, 'dict_from_cookiejar')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_dict_from_cookiejar__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_dict_from_cookiejar__property_based(a, b):
    try:
        _ = getattr(MOD, 'dict_from_cookiejar')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_add_dict_to_cookiejar__basic_smoke():
    try:
        out = getattr(MOD, 'add_dict_to_cookiejar')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_add_dict_to_cookiejar__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_add_dict_to_cookiejar__property_based(a, b):
    try:
        _ = getattr(MOD, 'add_dict_to_cookiejar')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get_encodings_from_content__basic_smoke():
    try:
        out = getattr(MOD, 'get_encodings_from_content')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_encodings_from_content__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_encodings_from_content__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_encodings_from_content')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get_encoding_from_headers__basic_smoke():
    try:
        out = getattr(MOD, 'get_encoding_from_headers')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_encoding_from_headers__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_encoding_from_headers__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_encoding_from_headers')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_stream_decode_response_unicode__basic_smoke():
    try:
        out = getattr(MOD, 'stream_decode_response_unicode')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_stream_decode_response_unicode__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_stream_decode_response_unicode__property_based(a, b):
    try:
        _ = getattr(MOD, 'stream_decode_response_unicode')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_iter_slices__basic_smoke():
    try:
        out = getattr(MOD, 'iter_slices')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_iter_slices__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_iter_slices__property_based(a, b):
    try:
        _ = getattr(MOD, 'iter_slices')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get_unicode_from_response__basic_smoke():
    try:
        out = getattr(MOD, 'get_unicode_from_response')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_unicode_from_response__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_unicode_from_response__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_unicode_from_response')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_unquote_unreserved__basic_smoke():
    try:
        out = getattr(MOD, 'unquote_unreserved')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_unquote_unreserved__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_unquote_unreserved__property_based(a, b):
    try:
        _ = getattr(MOD, 'unquote_unreserved')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_requote_uri__basic_smoke():
    try:
        out = getattr(MOD, 'requote_uri')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_requote_uri__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_requote_uri__property_based(a, b):
    try:
        _ = getattr(MOD, 'requote_uri')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_address_in_network__basic_smoke():
    try:
        out = getattr(MOD, 'address_in_network')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_address_in_network__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_address_in_network__property_based(a, b):
    try:
        _ = getattr(MOD, 'address_in_network')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_dotted_netmask__basic_smoke():
    try:
        out = getattr(MOD, 'dotted_netmask')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_dotted_netmask__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_dotted_netmask__property_based(a, b):
    try:
        _ = getattr(MOD, 'dotted_netmask')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_is_ipv4_address__basic_smoke():
    try:
        out = getattr(MOD, 'is_ipv4_address')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_is_ipv4_address__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_is_ipv4_address__property_based(a, b):
    try:
        _ = getattr(MOD, 'is_ipv4_address')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_is_valid_cidr__basic_smoke():
    try:
        out = getattr(MOD, 'is_valid_cidr')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_is_valid_cidr__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_is_valid_cidr__property_based(a, b):
    try:
        _ = getattr(MOD, 'is_valid_cidr')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_set_environ__basic_smoke():
    try:
        out = getattr(MOD, 'set_environ')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_set_environ__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_set_environ__property_based(a, b):
    try:
        _ = getattr(MOD, 'set_environ')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_should_bypass_proxies__basic_smoke():
    try:
        out = getattr(MOD, 'should_bypass_proxies')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_should_bypass_proxies__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_should_bypass_proxies__property_based(a, b):
    try:
        _ = getattr(MOD, 'should_bypass_proxies')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get_environ_proxies__basic_smoke():
    try:
        out = getattr(MOD, 'get_environ_proxies')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_environ_proxies__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_environ_proxies__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_environ_proxies')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_select_proxy__basic_smoke():
    try:
        out = getattr(MOD, 'select_proxy')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_select_proxy__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_select_proxy__property_based(a, b):
    try:
        _ = getattr(MOD, 'select_proxy')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_resolve_proxies__basic_smoke():
    try:
        out = getattr(MOD, 'resolve_proxies')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_resolve_proxies__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_resolve_proxies__property_based(a, b):
    try:
        _ = getattr(MOD, 'resolve_proxies')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_default_user_agent__basic_smoke():
    try:
        out = getattr(MOD, 'default_user_agent')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_default_user_agent__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_default_user_agent__property_based(a, b):
    try:
        _ = getattr(MOD, 'default_user_agent')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_default_headers__basic_smoke():
    try:
        out = getattr(MOD, 'default_headers')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_default_headers__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_default_headers__property_based(a, b):
    try:
        _ = getattr(MOD, 'default_headers')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_parse_header_links__basic_smoke():
    try:
        out = getattr(MOD, 'parse_header_links')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_parse_header_links__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_parse_header_links__property_based(a, b):
    try:
        _ = getattr(MOD, 'parse_header_links')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_guess_json_utf__basic_smoke():
    try:
        out = getattr(MOD, 'guess_json_utf')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_guess_json_utf__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_guess_json_utf__property_based(a, b):
    try:
        _ = getattr(MOD, 'guess_json_utf')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_prepend_scheme_if_needed__basic_smoke():
    try:
        out = getattr(MOD, 'prepend_scheme_if_needed')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_prepend_scheme_if_needed__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_prepend_scheme_if_needed__property_based(a, b):
    try:
        _ = getattr(MOD, 'prepend_scheme_if_needed')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get_auth_from_url__basic_smoke():
    try:
        out = getattr(MOD, 'get_auth_from_url')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_auth_from_url__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_auth_from_url__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_auth_from_url')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_check_header_validity__basic_smoke():
    try:
        out = getattr(MOD, 'check_header_validity')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_check_header_validity__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_check_header_validity__property_based(a, b):
    try:
        _ = getattr(MOD, 'check_header_validity')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_urldefragauth__basic_smoke():
    try:
        out = getattr(MOD, 'urldefragauth')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_urldefragauth__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_urldefragauth__property_based(a, b):
    try:
        _ = getattr(MOD, 'urldefragauth')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_rewind_body__basic_smoke():
    try:
        out = getattr(MOD, 'rewind_body')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_rewind_body__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_rewind_body__property_based(a, b):
    try:
        _ = getattr(MOD, 'rewind_body')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
