# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../TheAlgorithms__Python').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../TheAlgorithms__Python/cellular_automata/game_of_life.py'
MOD_NAME = 'mod_cellular_automata_game_of_life_a9023db1'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_create_canvas__basic_smoke():
    try:
        out = getattr(MOD, 'create_canvas')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_create_canvas__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_create_canvas__property_based(a, b):
    try:
        _ = getattr(MOD, 'create_canvas')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_seed__basic_smoke():
    try:
        out = getattr(MOD, 'seed')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_seed__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_seed__property_based(a, b):
    try:
        _ = getattr(MOD, 'seed')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_run__basic_smoke():
    try:
        out = getattr(MOD, 'run')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_run__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_run__property_based(a, b):
    try:
        _ = getattr(MOD, 'run')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
