# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../Netflix__security_monkey').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../Netflix__security_monkey/security_monkey/decorators.py'
MOD_NAME = 'mod_security_monkey_decorators_b73beade'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_crossdomain__basic_smoke():
    try:
        out = getattr(MOD, 'crossdomain')(None, None, None, None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_crossdomain__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_crossdomain__property_based(a, b):
    try:
        _ = getattr(MOD, 'crossdomain')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_record_exception__basic_smoke():
    try:
        out = getattr(MOD, 'record_exception')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_record_exception__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_record_exception__property_based(a, b):
    try:
        _ = getattr(MOD, 'record_exception')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_iter_account_region__basic_smoke():
    try:
        out = getattr(MOD, 'iter_account_region')(None, None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_iter_account_region__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_iter_account_region__property_based(a, b):
    try:
        _ = getattr(MOD, 'iter_account_region')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get_regions__basic_smoke():
    try:
        out = getattr(MOD, 'get_regions')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_regions__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_regions__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_regions')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
