# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../kennethreitz__requests').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../kennethreitz__requests/src/requests/cookies.py'
MOD_NAME = 'mod_src_requests_cookies_facf211c'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_extract_cookies_to_jar__basic_smoke():
    try:
        out = getattr(MOD, 'extract_cookies_to_jar')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_extract_cookies_to_jar__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_extract_cookies_to_jar__property_based(a, b):
    try:
        _ = getattr(MOD, 'extract_cookies_to_jar')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get_cookie_header__basic_smoke():
    try:
        out = getattr(MOD, 'get_cookie_header')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_cookie_header__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_cookie_header__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_cookie_header')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_remove_cookie_by_name__basic_smoke():
    try:
        out = getattr(MOD, 'remove_cookie_by_name')(None, None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_remove_cookie_by_name__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_remove_cookie_by_name__property_based(a, b):
    try:
        _ = getattr(MOD, 'remove_cookie_by_name')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_create_cookie__basic_smoke():
    try:
        out = getattr(MOD, 'create_cookie')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_create_cookie__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_create_cookie__property_based(a, b):
    try:
        _ = getattr(MOD, 'create_cookie')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_morsel_to_cookie__basic_smoke():
    try:
        out = getattr(MOD, 'morsel_to_cookie')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_morsel_to_cookie__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_morsel_to_cookie__property_based(a, b):
    try:
        _ = getattr(MOD, 'morsel_to_cookie')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_cookiejar_from_dict__basic_smoke():
    try:
        out = getattr(MOD, 'cookiejar_from_dict')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_cookiejar_from_dict__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_cookiejar_from_dict__property_based(a, b):
    try:
        _ = getattr(MOD, 'cookiejar_from_dict')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_merge_cookies__basic_smoke():
    try:
        out = getattr(MOD, 'merge_cookies')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_merge_cookies__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_merge_cookies__property_based(a, b):
    try:
        _ = getattr(MOD, 'merge_cookies')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
