# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../ageron__handson-ml').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '_notebooks/nb_01_the_machine_learning_landscape_da5f207e.py'
MOD_NAME = 'nb_01_the_machine_learning_landscape_da5f207e'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_save_fig__basic_smoke():
    try:
        out = getattr(MOD, 'save_fig')(None, None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_save_fig__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_save_fig__property_based(a, b):
    try:
        _ = getattr(MOD, 'save_fig')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_prepare_country_stats__basic_smoke():
    try:
        out = getattr(MOD, 'prepare_country_stats')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_prepare_country_stats__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_prepare_country_stats__property_based(a, b):
    try:
        _ = getattr(MOD, 'prepare_country_stats')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_prepare_country_stats__basic_smoke():
    try:
        out = getattr(MOD, 'prepare_country_stats')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_prepare_country_stats__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_prepare_country_stats__property_based(a, b):
    try:
        _ = getattr(MOD, 'prepare_country_stats')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_prepare_country_stats__basic_smoke():
    try:
        out = getattr(MOD, 'prepare_country_stats')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_prepare_country_stats__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_prepare_country_stats__property_based(a, b):
    try:
        _ = getattr(MOD, 'prepare_country_stats')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
