# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../ageron__handson-ml').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../ageron__handson-ml/docker/jupyter_notebook_config.py'
MOD_NAME = 'mod_docker_jupyter_notebook_config_a702025f'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_export_script_and_view__basic_smoke():
    try:
        out = getattr(MOD, 'export_script_and_view')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_export_script_and_view__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_export_script_and_view__property_based(a, b):
    try:
        _ = getattr(MOD, 'export_script_and_view')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
