# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../kennethreitz__requests').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../kennethreitz__requests/src/requests/hooks.py'
MOD_NAME = 'mod_src_requests_hooks_8dd95f9a'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_default_hooks__basic_smoke():
    try:
        out = getattr(MOD, 'default_hooks')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_default_hooks__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_default_hooks__property_based(a, b):
    try:
        _ = getattr(MOD, 'default_hooks')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_dispatch_hook__basic_smoke():
    try:
        out = getattr(MOD, 'dispatch_hook')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_dispatch_hook__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_dispatch_hook__property_based(a, b):
    try:
        _ = getattr(MOD, 'dispatch_hook')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
