# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../Netflix__security_monkey').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../Netflix__security_monkey/security_monkey/monitors.py'
MOD_NAME = 'mod_security_monkey_monitors_186dc504'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_get_monitors__basic_smoke():
    try:
        out = getattr(MOD, 'get_monitors')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_monitors__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_monitors__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_monitors')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_get_monitors_and_dependencies__basic_smoke():
    try:
        out = getattr(MOD, 'get_monitors_and_dependencies')(None, None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_get_monitors_and_dependencies__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_get_monitors_and_dependencies__property_based(a, b):
    try:
        _ = getattr(MOD, 'get_monitors_and_dependencies')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_all_monitors__basic_smoke():
    try:
        out = getattr(MOD, 'all_monitors')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_all_monitors__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_all_monitors__property_based(a, b):
    try:
        _ = getattr(MOD, 'all_monitors')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
