# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../kennethreitz__requests').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../kennethreitz__requests/src/requests/help.py'
MOD_NAME = 'mod_src_requests_help_c3c96fdd'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_info__basic_smoke():
    try:
        out = getattr(MOD, 'info')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_info__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_info__property_based(a, b):
    try:
        _ = getattr(MOD, 'info')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_main__basic_smoke():
    try:
        out = getattr(MOD, 'main')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_main__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_main__property_based(a, b):
    try:
        _ = getattr(MOD, 'main')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
