# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../pallets__flask').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../pallets__flask/src/flask/json/__init__.py'
MOD_NAME = 'mod_src_flask_json___init_6405bca7'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_dumps__basic_smoke():
    try:
        out = getattr(MOD, 'dumps')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_dumps__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_dumps__property_based(a, b):
    try:
        _ = getattr(MOD, 'dumps')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_dump__basic_smoke():
    try:
        out = getattr(MOD, 'dump')(None, None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_dump__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_dump__property_based(a, b):
    try:
        _ = getattr(MOD, 'dump')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_loads__basic_smoke():
    try:
        out = getattr(MOD, 'loads')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_loads__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_loads__property_based(a, b):
    try:
        _ = getattr(MOD, 'loads')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_load__basic_smoke():
    try:
        out = getattr(MOD, 'load')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_load__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_load__property_based(a, b):
    try:
        _ = getattr(MOD, 'load')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_jsonify__basic_smoke():
    try:
        out = getattr(MOD, 'jsonify')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_jsonify__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_jsonify__property_based(a, b):
    try:
        _ = getattr(MOD, 'jsonify')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
