# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../pallets__flask').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../pallets__flask/examples/tutorial/flaskr/auth.py'
MOD_NAME = 'mod_examples_tutorial_flaskr_auth_77fe82c0'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_login_required__basic_smoke():
    try:
        out = getattr(MOD, 'login_required')(None)
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_login_required__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_login_required__property_based(a, b):
    try:
        _ = getattr(MOD, 'login_required')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_load_logged_in_user__basic_smoke():
    try:
        out = getattr(MOD, 'load_logged_in_user')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_load_logged_in_user__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_load_logged_in_user__property_based(a, b):
    try:
        _ = getattr(MOD, 'load_logged_in_user')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_register__basic_smoke():
    try:
        out = getattr(MOD, 'register')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_register__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_register__property_based(a, b):
    try:
        _ = getattr(MOD, 'register')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_login__basic_smoke():
    try:
        out = getattr(MOD, 'login')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_login__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_login__property_based(a, b):
    try:
        _ = getattr(MOD, 'login')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_logout__basic_smoke():
    try:
        out = getattr(MOD, 'logout')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_logout__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_logout__property_based(a, b):
    try:
        _ = getattr(MOD, 'logout')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
