# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import sys
from pathlib import Path

REPO_ROOT = (Path(__file__).parent / '../Netflix__security_monkey').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
REPO_SRC = REPO_ROOT / 'src'
if REPO_SRC.exists() and str(REPO_SRC) not in sys.path:
    sys.path.insert(0, str(REPO_SRC))

import importlib.util
from pathlib import Path

MOD_PATH = Path(__file__).parent / '../Netflix__security_monkey/migrations/env.py'
MOD_NAME = 'mod_migrations_env_1d5e98f8'
spec = importlib.util.spec_from_file_location(MOD_NAME, MOD_PATH)
MOD = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(MOD)



def test_run_migrations_offline__basic_smoke():
    try:
        out = getattr(MOD, 'run_migrations_offline')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_run_migrations_offline__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_run_migrations_offline__property_based(a, b):
    try:
        _ = getattr(MOD, 'run_migrations_offline')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_run_migrations_online__basic_smoke():
    try:
        out = getattr(MOD, 'run_migrations_online')()
    except TypeError:
        pytest.skip('signature mismatch for template call')
        return
    assert out is not None or out is None



def test_run_migrations_online__edge_cases():
    # TODO: add domain-specific edge cases when known
    assert True

@given(st.integers(), st.integers())
def test_run_migrations_online__property_based(a, b):
    try:
        _ = getattr(MOD, 'run_migrations_online')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
