# Auto-generated by CodeAssistant
import pytest

from hypothesis import given, strategies as st

import importlib

MOD = importlib.import_module('pandas\pandas\compat\numpy\function')



def test_process_skipna__basic_smoke():
    # TODO: 根据真实语义替换 None，补充断言
    out = getattr(MOD, 'process_skipna')(None, None)
    assert out is not None or out is None



def test_process_skipna__edge_cases():
    # TODO: 空输入/极值/非法类型/异常路径
    assert True


@given(st.integers(), st.integers())
def test_process_skipna__property_based(a, b):
    try:
        _ = getattr(MOD, 'process_skipna')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_validate_argmin_with_skipna__basic_smoke():
    # TODO: 根据真实语义替换 None，补充断言
    out = getattr(MOD, 'validate_argmin_with_skipna')(None, None, None)
    assert out is not None or out is None



def test_validate_argmin_with_skipna__edge_cases():
    # TODO: 空输入/极值/非法类型/异常路径
    assert True


@given(st.integers(), st.integers())
def test_validate_argmin_with_skipna__property_based(a, b):
    try:
        _ = getattr(MOD, 'validate_argmin_with_skipna')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_validate_argmax_with_skipna__basic_smoke():
    # TODO: 根据真实语义替换 None，补充断言
    out = getattr(MOD, 'validate_argmax_with_skipna')(None, None, None)
    assert out is not None or out is None



def test_validate_argmax_with_skipna__edge_cases():
    # TODO: 空输入/极值/非法类型/异常路径
    assert True


@given(st.integers(), st.integers())
def test_validate_argmax_with_skipna__property_based(a, b):
    try:
        _ = getattr(MOD, 'validate_argmax_with_skipna')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_validate_argsort_with_ascending__basic_smoke():
    # TODO: 根据真实语义替换 None，补充断言
    out = getattr(MOD, 'validate_argsort_with_ascending')(None, None, None)
    assert out is not None or out is None



def test_validate_argsort_with_ascending__edge_cases():
    # TODO: 空输入/极值/非法类型/异常路径
    assert True


@given(st.integers(), st.integers())
def test_validate_argsort_with_ascending__property_based(a, b):
    try:
        _ = getattr(MOD, 'validate_argsort_with_ascending')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_validate_clip_with_axis__basic_smoke():
    # TODO: 根据真实语义替换 None，补充断言
    out = getattr(MOD, 'validate_clip_with_axis')(None, None, None)
    assert out is not None or out is None



def test_validate_clip_with_axis__edge_cases():
    # TODO: 空输入/极值/非法类型/异常路径
    assert True


@given(st.integers(), st.integers())
def test_validate_clip_with_axis__property_based(a, b):
    try:
        _ = getattr(MOD, 'validate_clip_with_axis')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_validate_clip_with_axis__basic_smoke():
    # TODO: 根据真实语义替换 None，补充断言
    out = getattr(MOD, 'validate_clip_with_axis')(None, None, None)
    assert out is not None or out is None



def test_validate_clip_with_axis__edge_cases():
    # TODO: 空输入/极值/非法类型/异常路径
    assert True


@given(st.integers(), st.integers())
def test_validate_clip_with_axis__property_based(a, b):
    try:
        _ = getattr(MOD, 'validate_clip_with_axis')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')



def test_validate_clip_with_axis__basic_smoke():
    # TODO: 根据真实语义替换 None，补充断言
    out = getattr(MOD, 'validate_clip_with_axis')(None, None, None)
    assert out is not None or out is None



def test_validate_clip_with_axis__edge_cases():
    # TODO: 空输入/极值/非法类型/异常路径
    assert True


@given(st.integers(), st.integers())
def test_validate_clip_with_axis__property_based(a, b):
    try:
        _ = getattr(MOD, 'validate_clip_with_axis')(a, b)
    except TypeError:
        pytest.skip('signature mismatch for hypothesis template')
